# Generated by Django 5.1.4 on 2024-12-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('done_quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
