# Generated by Django 5.1.4 on 2025-01-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='working_cell',
            field=models.IntegerField(default=0),
        ),
    ]
