# Generated by Django 5.1.4 on 2025-01-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='started_job',
            field=models.BooleanField(default=False),
        ),
    ]
