# Generated by Django 5.1.4 on 2025-01-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0002_cell_started_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cell',
            name='started_job',
        ),
        migrations.AddField(
            model_name='cell',
            name='job',
            field=models.CharField(default=''),
        ),
    ]
