# Generated by Django 5.1.4 on 2024-12-25 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0001_initial'),
        ('employees', '0002_employee_cell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='cell',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='cells.cell'),
        ),
    ]
