# Generated by Django 5.1.4 on 2024-12-25 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0001_initial'),
        ('employees', '0003_alter_employee_cell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='cell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='cells.cell'),
        ),
    ]
